import Head from 'next/head';
import React, { useContext, useState } from 'react';
import AdminAccessContent from '../../components/BLOG/AdminAccess/AdminAccessContent';
import AdminAccessDrawerMenu from '../../components/BLOG/AdminAccess/AdminAccessDrawerMenu';
import NotFound from '../../components/BLOG/NotFound';
import Header from '../../components/Header/Header';
import PageTitle from '../../components/hooks/PageTitle';
import LoadingSpin from '../../components/LoadingSpin';
import { MenuBarRight } from '../../components/ReactRSIcon';
import { UserFullInfoProvider } from '../_app';


const Index = () => {
    const { title } = PageTitle()
    const [selectServices, setSelectServices] = useState('CONTENT DELIVERY NETWORK (CDN) CODE')

    const { user, user_details, isLoading, isAdmin } = useContext(UserFullInfoProvider);
    const [selectOptionAccess, setSelectOptionAccess] = useState('')
    if (isLoading) {
        return <div className='min-h-screen'>
            <LoadingSpin />
        </div>
    }

    if(!isAdmin?.admin){
        return <NotFound/>
    }
    return (
        <div className='h-full bg-base-100 '>
            <Head>
                {/* */}
                <title>
                    {title} 🡂 Service
                    {
                        selectServices && ' 🡂 ' + selectServices
                    }
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <div className="drawer drawer-mobile m-0">
                    <input id="servicesDrawer" type="checkbox" className="drawer-toggle" />
                    <div className="drawer-content p-1">
                        <div className='text-end pr-2 pt-1'>
                            <label
                                htmlFor="servicesDrawer"
                                className="btn btn-primary btn-xs btn-outline drawer-button lg:hidden "
                            >
                                <MenuBarRight />
                            </label>
                        </div>

                        <div className='h-full overflow-auto hideScrollBar'>
                            <AdminAccessContent/>
                        </div>
                    </div>
                    <div className="drawer-side border-r-[1px] border-gray-500 ">
                        <label htmlFor="servicesDrawer" className="drawer-overlay"></label>
                        <AdminAccessDrawerMenu selectOptionAccess={selectOptionAccess} setSelectOptionAccess={setSelectOptionAccess} />

                    </div>
                </div>
            </div>
        </div>
    );
};

export default Index;