import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import { useQuery } from 'react-query';
import Header from '../../../components/Header/Header';
import PageTitle from '../../../components/hooks/PageTitle';
import CdnCodeList from '../../../components/Services/CDN_CODE/CdnCodeList';

const Index = () => {
    const router = useRouter()
    const { user_id, cdn_id } = router.query;
    const $code_id = cdn_id + '-' + user_id
    const { data, isLoading, refetch } = useQuery(['CDN_CODE_SPECIFIED', user_id, cdn_id, $code_id], () => axios.get(`/api/services/cdn/cdn-one?code_id=${$code_id}`,
        {
            headers: { access_token: sessionStorage.getItem('accessAutoG') }
        }
    ))
    const codeBody = data?.data?.result || {}
    const { title } = PageTitle()

    return (
        <div>
            <Head>
                <title>
                    {title} 🡂 Services 🡂 CDN 🡂 {codeBody?.code_title}
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='h-full bg-base-100 pb-10'>
                <Header />
                <div className='lg:pl-20'>
                    {
                        <CdnCodeList cdn={codeBody} index={0} refetch={refetch} />
                    }
                </div>
            </div>
        </div>
    );
};

export default Index;