import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useContext } from 'react';
import { useQuery } from 'react-query';
import Header from '../../../components/Header/Header';
import PageTitle from '../../../components/hooks/PageTitle';
import LoadingSpin from '../../../components/LoadingSpin';
import CdnCodeList from '../../../components/Services/CDN_CODE/CdnCodeList';
import { UserFullInfoProvider } from '../../_app';

const Index = () => {
    const router = useRouter()
    const { user_id, cdn_id } = router.query;
    const $code_id = cdn_id + '-' + user_id
    const { data, isLoading, refetch } = useQuery(['CDN_CODE_SPECIFIED', user_id, cdn_id, $code_id], () => axios.get(`/api/services/cdn/cdn-one?code_id=${$code_id}`,
        {
            headers: { access_token: sessionStorage.getItem('accessAutoG') }
        }
    ))
    const codeBody = data?.data?.result || {}
    const { title } = PageTitle()

    const { user, user_details, isLoading: userLoading, isAdmin } = useContext(UserFullInfoProvider);
    if (userLoading) {
        return <div className='min-h-screen'>
            <LoadingSpin />
        </div>
    }
    return (
        <div>
            <Head>
                <title>
                    {title} 🡂 Services 🡂 CDN 🡂 {codeBody?.code_title}
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='h-full bg-base-100 pb-10'>
                {
                    isLoading ? <LoadingSpin />
                        :
                        <div className='lg:pl-20'>
                            {
                                <CdnCodeList cdn={codeBody} index={0} refetch={refetch} />
                            }
                        </div>
                }
            </div>
        </div>
    );
};

export default Index;

// export async function getServerSideProps(context) {
//     const { cdn_id, user_id } = context.query;
//     const $code_id = cdn_id + '-' + user_id;
//     const cookies = context.req.headers?.cookie?.split('=')?.[1] || ''
//     // const url = `https://prog-learn.vercel.app/api/post/find-specific-story?post_id=${id}`
//     const url = `${process.env.host}/api/services/cdn/cdn-one?code_id=${$code_id}`

//     const { data } = await axios(url, {
//         headers: { access_token: cookies }
//     })
//     // // const data = await fetchData.json()

//     if (Object.keys(data).length == 2) {
//         return {
//             notFound: true,
//         }
//     }
//     // Pass data to the page via props
//     return { props: { data: "data" } }
// }
