import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useContext, useEffect } from 'react';
import { useQuery } from 'react-query';
import AdsRightSide from '../../../components/Ads/AdsRightSide';
import PageDetailsSEO from '../../../components/BLOG/hooks/PageDetailsSEO';
import SinglePost from '../../../components/BLOG/post/single-post/SinglePost';
import LoadingPost from '../../../components/LoadingPost';
import LoadingSpin from '../../../components/LoadingSpin';
import { UserFullInfoProvider } from '../../_app';


const Index = () => {
    const router = useRouter();
    const { id } = router.query;
    // find-specific-story
    const { data, refetch, isLoading } = useQuery(['find-specific-story', id], () => axios.get(`/api/post/find-specific-story?post_id=${id}`,
        {
            headers: { access_token: sessionStorage.getItem('accessAutoG') }
        }
    ))
    const post = data?.data || {}
    useEffect(() => {
        window.scrollTo(0, 0)
    }, [])

    const { title } = PageDetailsSEO()
    const { user, user_details, isLoading: userLoading, isAdmin } = useContext(UserFullInfoProvider);
    if (userLoading) {
        return <div className='min-h-screen'>
            <LoadingSpin />
        </div>
    }
    return (

        <div className='grid grid-cols-12'>
            <Head>
                <title>{title + '>' + post?.post_title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='col-span-12  lg:col-span-7  2xl:col-span-9 mb-20'>
                <div>
                    {
                        isLoading ?
                            <div className='mt-20'>
                                <LoadingPost />
                            </div>
                            :
                            <SinglePost post={post} refetch={refetch} />
                    }
                </div>
            </div>
            <div className='hidden ml-2 pl-4 shadow-md lg:block col-span-12 lg:col-span-5  2xl:col-span-3 text-justify mb-20 rounded-md'>
               <AdsRightSide/>
            </div>
        </div>
    );
};

export default Index;