import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import Header from '../components/Header/Header';
import Link from 'next/link';
import Home from '../components/Home/Home';
export default function Index() {

  return (
    <div data-scroll='[green, ,]' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className='md:ml-16'>
        <div className='bg-base-100 p-2'>
          <Home/>
        </div>
      </div>
    </div>
  )
}