import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import Header from '../components/Header/Header';
import Link from 'next/link';
export default function Home() {

  return (
    <div data-scroll='[green, ,]' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className='md:ml-16'>
        <div className='bg-base-100 p-2'>

          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto omnis repudiandae qui! Quibusdam, amet fugiat eaque veritatis adipisci nostrum dolor obcaecati earum asperiores et distinctio libero officia nulla dolorem quam!
          Asperiores tempore nam animi ipsa vitae porro voluptatem tempora quidem obcaecati, laudantium veritatis harum! Fugit quaerat quo, sapiente veniam iste obcaecati dicta unde autem, ducimus atque officiis neque laborum qui.
          Placeat id enim totam facere deserunt ex cupiditate doloremque, dolor mollitia sit vero ad, suscipit illo fugit quod eius tenetur hic nostrum delectus asperiores vitae necessitatibus. Laboriosam impedit est rerum!
          Dolores dolore doloribus necessitatibus nostrum est consequatur sunt magnam? Molestiae aut non possimus totam nostrum quos sint, pariatur placeat, tenetur in fugiat. At molestias fuga, dolorem accusamus maiores exercitationem voluptatibus.
          Hic similique voluptate natus laborum magnam minima eum, animi quo voluptatem molestias quibusdam nisi. Incidunt consectetur, alias rerum error fugiat quidem possimus tempore vero accusantium obcaecati odit modi dolores eligendi!
          Asperiores dignissimos labore modi, quibusdam repellendus expedita, soluta fuga explicabo, ut vero doloremque! Sed, corrupti fugiat qui numquam dolores aspernatur aliquid? Voluptatem sit odio libero asperiores tempore blanditiis alias! Dolorum.
          Omnis nam laudantium assumenda! Quod tempora nemo fugiat. Odio voluptatibus placeat hic dignissimos accusamus, facere doloribus corporis error harum, magni quos delectus reiciendis sint tempora laboriosam officiis excepturi nostrum molestiae.
          Impedit dolore maxime iste eveniet ad illo molestias quia voluptates esse veniam. Dignissimos ex quod commodi culpa accusantium aliquam veniam quisquam non est perferendis. Vero temporibus ducimus similique repudiandae quidem?
          Eveniet ipsum nobis deleniti nemo. Accusamus illo nulla impedit veniam minus, consequuntur dolor temporibus tempore necessitatibus quibusdam maiores error quos eligendi dolores dolore ut. Tempora repudiandae minus rem cupiditate inventore?
          Sunt, corporis! Architecto nam nisi doloribus! Nemo alias ratione quasi ipsum quod, quis aut earum molestias voluptate saepe, perspiciatis, cum aspernatur nobis reiciendis odit doloremque culpa ut esse molestiae sit.
        </div>
      </div>
    </div>
  )
}